import {Genome} from '../stores/bio/types';

export const mockedMe: Genome = {
  "person": {
    "professionalHeadline": "Senior Mobile Architect",
    "completion": 0.5556,
    "showPhone": false,
    "verified": true,
    "weight": 188.6701,
    "locale": "en",
    "picture": "https://starrgate.s3.amazonaws.com:443/users/6dc1d544541c4657ab38ce145c63959718ad300a/profile_oVzwTYG.jpg",
    "name": "Sergio Daniel",
    "links": [
      {
        "id": "bjAYGqjX",
        "name": "instagram",
        "address": "https://instagram.com/lordzheref"
      },
      {
        "id": "8jplwvjX",
        "name": "github",
        "address": "https://github.com/zheref"
      },
      {
        "id": "OMvaLEN8",
        "name": "linkedin",
        "address": "https://www.linkedin.com/in/zheref/"
      },
      {
        "id": "XMqkE7y5",
        "name": "facebook",
        "address": "https://facebook.com/zheref"
      },
      {
        "id": "pyJPQgMJ",
        "name": "twitter",
        "address": "https://twitter.com/zheref"
      }
    ],
    "location": {
      "name": "Antioquia, Colombia",
      "shortName": "Medellin, Antioquia, Colombia",
      "country": "Colombia",
      "latitude": 6.2476376,
      "longitude": -75.5658153,
      "timezone": "America/Bogota",
      "timezoneOffSet": -18000000
    },
    "pictureThumbnail": "https://starrgate.s3.amazonaws.com:443/CACHE/images/users/6dc1d544541c4657ab38ce145c63959718ad300a/profile_oVzwTYG/45ce9e0b3f43f843260e32701476007f.jpg",
    "summaryOfBio": "Software developer specializing in mobile user experiences with more than 8 years of experience in the market. He's been mostly self-taught and has been coding since he was 9 years old. He's fast, flexible and change-ready for today’s evolving tech and any upcoming challenge. Also very fast learning new technologies like languages, frameworks, tools and others.\nVery proficient implanting solid software architectures and patterns as well as following design principles for maintainable software including S.O.L.I.D. He's great at version control, continuous integration, continuous delivery, test-driven development, package managers, agile development (Scrum and Kanban), among others industry-class practices.\nHe's always looking for remarkable ideas and products to work on and take the world even further. He's also a geek who loves dogs, dragons, playing videogames, traveling around the world and meeting new people.",
    "weightGraph": "https://hcti.io/v1/image/47c687de-c445-49c9-b267-61dc70140fd4",
    "publicId": "zheref"
  },
  "stats": {
    "jobs": 8,
    "education": 1,
    "strengths": 55,
    "interests": 3
  },
  "strengths": [
    {
      "id": "kybn7Z7y",
      "code": 18549,
      "name": "TeamCity",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "Oj6YV3AM",
      "code": 18374,
      "name": "GitHub",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "7M2WRz1j",
      "code": 71238,
      "name": "Carthage",
      "weight": 0,
      "recommendations": 0,

    },
    {
      "id": "zNG6R1oy",
      "code": 18380,
      "name": "JIRA",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "qNPLe12N",
      "code": 116293,
      "name": "Bitbucket",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "0yzRoGay",
      "code": 6586750,
      "name": "Xcode Instruments",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "vN8xReYN",
      "code": 54652,
      "name": "Viper",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "LMgn2pJN",
      "code": 54281,
      "name": "UML",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "pyJwR1kN",
      "code": 17252,
      "name": "CocoaPods",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "XMqno79j",
      "code": 9486,
      "name": "GIT",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "OMvBoG9M",
      "code": 94433,
      "name": "XCTest",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "8jpnoD9N",
      "code": 6586715,
      "name": "SnapKit",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "bjAwRzvN",
      "code": 191979,
      "name": "Alamofire",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "JMen4baj",
      "code": 52344,
      "name": "SOLID",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "kNmno7XM",
      "code": 32049,
      "name": "Objective C",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "EM3DRXmj",
      "code": 57125,
      "name": "iOS development",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "ZNObmX0y",
      "code": 55684,
      "name": "UX design",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "xM91RmwM",
      "code": 32024,
      "name": "Dart",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "9MBwO8lj",
      "code": 26687,
      "name": "Flutter",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "WNVLgP0j",
      "code": 6586704,
      "name": "Bitrise",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "eynno7Ry",
      "code": 51526,
      "name": "Sentry",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "pyonoVAj",
      "code": 6586703,
      "name": "Instabug",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "ny1kdJBM",
      "code": 55909,
      "name": "Jest",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "kybn7G7y",
      "code": 6085970,
      "name": "Test driven development",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "AjrnoVdj",
      "code": 6586700,
      "name": "Fitbit SDK",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "ANanK41M",
      "code": 4294724,
      "name": "Redux Persist",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "vy5GRz4M",
      "code": 4555981,
      "name": "Redux Thunk",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "JyQLAz6j",
      "code": 4345215,
      "name": "Reactive Programming",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "9MEwoZQy",
      "code": 6081935,
      "name": "Functional programming",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "VjwR9YGM",
      "code": 6586692,
      "name": "Framer X",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "GNKwRvXN",
      "code": 130359,
      "name": "Google analytics",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "qy086qqy",
      "code": 118992,
      "name": "Swift 4",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "pyJwRpkN",
      "code": 43524,
      "name": "Google APIs",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "XMqnol9j",
      "code": 34399,
      "name": "Facebook API",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "OMvBoE9M",
      "code": 55243,
      "name": "CI/CD",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "8jpnoY9N",
      "code": 6586653,
      "name": "Buddybuild",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "bjAwRXvN",
      "code": 620066,
      "name": "Redux Saga",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "JMen47aj",
      "code": 50289,
      "name": "Redux",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "EM3DRKmj",
      "code": 32590,
      "name": "TypeScript",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "8yZLWX0M",
      "code": 50183,
      "name": "React Native",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "xyXL8Jky",
      "code": 34500,
      "name": "Scrum",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "pyJwRaWN",
      "code": 42441,
      "name": "Fastlane",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "XMqnoqJj",
      "code": 28888,
      "name": "REST",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "OMvBoz3M",
      "code": 19248,
      "name": "Google Cloud Platform",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "bjAwR5DN",
      "code": 19243,
      "name": "Firebase",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "pyonopZj",
      "code": 47095,
      "name": "MVVM",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "7M2WRk8j",
      "code": 54260,
      "name": "UIKit",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "vy5e64yY",
      "code": 114206,
      "name": "Excellent problem-solving skills",
      "weight": 62.8399,
      "recommendations": 1,
    },
    {
      "id": "BMLeKVjD",
      "code": 55644,
      "name": "Tech leadership",
      "weight": 62.8399,
      "recommendations": 1,
    },
    {
      "id": "KNx3AkyE",
      "code": 55906,
      "name": "Java",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "qy07wqjg",
      "code": 24450,
      "name": "Android",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "gyYGegMP",
      "code": 754,
      "name": "SWIFT",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "LMgqLJyE",
      "code": 17078,
      "name": "IOS",
      "weight": 62.8399,
      "recommendations": 1,
    },
    {
      "id": "xyXPWYyq",
      "code": 47084,
      "name": "MVC",
      "weight": 0,
      "recommendations": 0,
    },
    {
      "id": "AMWDz1jn",
      "code": 55424,
      "name": "Early adopter",
      "weight": 0.1504,
      "recommendations": 1,
    }
  ],
}

export async function fetchBio(handle: string): Promise<Genome | null> {
  return mockedMe;
}